apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookl
  template:
    metadata:
      labels:
        app: cookl
    spec:
      containers:
      - image: okteto.dev/cookl:latest
        name: cookl
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c1f903de-aeff-4aa2-81d9-f7cd6131ef8b"
        - name: Vless_Path
          value: "/vl7hh77"
        - name: Vmess_UUID
          value: "c1f903de-aeff-4aa2-81d9-f7cd6131ef8b"
        - name: Vmess_Path
          value: "/vmv8hh88"
        - name: Share_Path
          value: "/v2link"
